# Generated by Django 4.2 on 2024-09-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="postcord",
            new_name="postcode",
        ),
    ]
