# Generated by Django 4.2 on 2024-10-16 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="base_score",
        ),
    ]
