# Generated by Django 4.2 on 2024-10-16 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "checklist",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("quality", "품질이 우수해요"),
                            ("good_value", "합리적인 가격이에요"),
                            ("durability", "내구성이 뛰어나요"),
                            ("customer_service", "친절하고 매너가 좋아요"),
                            ("good_delivery", "거래약속을 잘 지켜요"),
                            ("bad_quality", "사진과 너무 달라요"),
                            ("bad_value", "돈이 아까워요"),
                            ("broken", "못 쓸 걸 팔았어요"),
                            ("bad_service", "불친절하게 느껴졌어요"),
                            ("bad_delivery", "시간을 안 지켜요"),
                        ],
                        max_length=114,
                    ),
                ),
                ("additional_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("score", models.FloatField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                ("is_score_assigned", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewed_product",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
