# Generated by Django 4.2 on 2024-10-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="base_score",
            field=models.FloatField(default=25),
        ),
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
