# Generated by Django 4.2 on 2024-10-11 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="checklist",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("quality", "품질이 우수해요"),
                    ("good_value", "합리적인 가격이에요"),
                    ("durability", "내구성이 뛰어나요"),
                    ("customer_service", "친절하고 매너가 좋아요"),
                    ("good_delivery", "거래약속을 잘 지켜요"),
                    ("bad_quality", "영 좋지 않아요"),
                    ("bad_value", "돈이 아까워요"),
                    ("broken", "못 쓸 걸 팔았어요"),
                    ("bad_service", "불친절하게 느껴졌어요"),
                    ("bad_delivery", "시간을 안 지켜요"),
                ],
                max_length=114,
            ),
        ),
    ]
