# Generated by Django 4.2 on 2024-10-17 03:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="checklist",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("품질이 우수해요", "품질이 우수해요"),
                    ("합리적인 가격이에요", "합리적인 가격이에요"),
                    ("내구성이 뛰어나요", "내구성이 뛰어나요"),
                    ("친절하고 매너가 좋아요", "친절하고 매너가 좋아요"),
                    ("거래약속을 잘 지켜요", "거래약속을 잘 지켜요"),
                    ("사진과 너무 달라요", "사진과 너무 달라요"),
                    ("돈이 아까워요", "돈이 아까워요"),
                    ("못 쓸 걸 팔았어요", "못 쓸 걸 팔았어요"),
                    ("불친절하게 느껴졌어요", "불친절하게 느껴졌어요"),
                    ("시간을 안 지켜요", "시간을 안 지켜요"),
                ],
                max_length=106,
            ),
        ),
    ]
