# Generated by Django 4.2 on 2024-10-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_review_author_alter_review_checklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.FloatField(),
        ),
    ]
