# Generated by Django 4.2 on 2024-10-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="score",
            field=models.FloatField(default=0),
        ),
    ]
