# Generated by Django 4.2 on 2024-12-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="static/images/default_profile.jpg",
                upload_to="images/",
            ),
        ),
    ]
