# Generated by Django 4.2 on 2024-09-27 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="like_products", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
