# Generated by Django 4.2 on 2024-10-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="buyer_profile",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="seller_profile",
        ),
    ]
