# Generated by Django 4.2 on 2024-09-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('s', '판매중'), ('r', '예약중'), ('c', '판매완료')], max_length=1),
        ),
    ]
