# Generated by Django 4.2 on 2024-10-21 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="exited_users",
            field=models.ManyToManyField(
                blank=True, related_name="exited_chatrooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
