# Generated by Django 4.2 on 2024-10-21 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_chatroom_exited_users_alter_hashtag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="review_requested",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="status_complate",
        ),
    ]
