# Generated by Django 4.2 on 2024-09-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('sell', '판매중'), ('reservation', '예약중'), ('complete', '판매완료')], max_length=50),
        ),
    ]
