# Generated by Django 4.2 on 2024-10-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PrivateComment",
        ),
    ]
