# Generated by Django 4.2 on 2024-09-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.hashtag'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
