# Generated by Django 4.2 on 2024-09-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_tags_alter_hashtag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hits',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
